server:
  port: 8080



spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: storing-service
          uri: lb://STORING-SERVICE
          predicates:
            - Path=/api/storing/**

        - id: analysis-service
          uri: lb://ANALYSIS-SERVICE
          predicates:
            - Path=/api/analysis/**

        - id: default-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/**
          filters:
            - SetStatus=404

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}